services:
  web:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: sec-analyzer-web
    ports:
      - "3080:3000"
    environment:
      - NODE_ENV=production
    volumes:
      - ./data:/app/data
    restart: unless-stopped
